spring:
  config:
    import: "optional:classpath:env.properties"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 day in milliseconds

openai:
  secret: ${OPENAI_KEY}