spring:
  config:
    import: "optional:classpath:env.properties"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret: "your_very_secure_and_long_secret_key_here"
  expiration: ${JWT_EXPIRATION:86400000}  # Optional fallback

openai:
  secret: ${OPENAI_KEY}
